### ISSUE TITLE
Condaがないと怒られる。

### ISSUE THREAD

**Issue by tacsotai** [smly/kaggle-book-gokui#13]
https://github.com/smly/kaggle-book-gokui/tree/main/chapter3 のREADME通りに進めている。
```
$ DATA_DIR=/data ./run.sh python ./run_all.py --data_dir=/data
+ docker build .
[+] Building 0.6s (8/8) FINISHED
 => [internal] load .dockerignore                                                                           0.0s
 => => transferring context: 68B                                                                            0.0s
 => [internal] load build definition from Dockerfile                                                        0.0s
 => => transferring dockerfile: 149B                                                                        0.0s
 => [internal] load metadata for docker.io/pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime                    0.6s
 => [internal] load build context                                                                           0.0s
 => => transferring context: 38B                                                                            0.0s
 => [1/3] FROM docker.io/pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime@sha256:9ebb176339b25a2d155e6f127c59  0.0s
 => CACHED [2/3] COPY requirements.txt .                                                                    0.0s
 => CACHED [3/3] RUN pip install -r requirements.txt                                                        0.0s
 => exporting to image                                                                                      0.0s
 => => exporting layers                                                                                     0.0s
 => => writing image sha256:14319c3bfec163f1fb3be1a50a0c270f42b1ae696d9c9b8d36fe985b97d47c0b                0.0s
+ docker build -q .
+ DOCKER_IMAGE=sha256:14319c3bfec163f1fb3be1a50a0c270f42b1ae696d9c9b8d36fe985b97d47c0b
+ docker run --gpus all --rm -v /home/tac/kaggle-book-gokui/chapter3:/workspace -v /data:/data -v /home/tac/.kaggle:/root/.kaggle -e TORCH_HOME=/workspace/.cache/torch/ --shm-size=2gb -it sha256:14319c3bfec163f1fb3be1a50a0c270f42b1ae696d9c9b8d36fe985b97d47c0b python ./run_all.py --data_dir=/data
Out dir: out/runall_2023-02-27_09-13-02
Configs: ['5', '6', '7-1', '7-3', '8-1', '8-2', '9-1']
Traceback (most recent call last):
  File "train.py", line 975, in <module>
    main()
  File "train.py", line 957, in main
    run_5(data_dir, out_dir, dryrun, device)
  File "train.py", line 455, in run_5
    model = train_subsec5(data_dir, batch_size, dryrun, device)
  File "train.py", line 432, in train_subsec5
    train_loader, val_loader = setup_train_val_loaders(
  File "train.py", line 97, in setup_train_val_loaders
    train_dataset, val_dataset = setup_train_val_datasets(
  File "train.py", line 60, in setup_train_val_datasets
    dataset = torchvision.datasets.ImageFolder(
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 253, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 132, in __init__
    raise RuntimeError(msg)
RuntimeError: Found 0 files in subfolders of: /data/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp
Traceback (most recent call last):
  File "./run_all.py", line 122, in <module>
    main()
  File "./run_all.py", line 82, in main
    val_report = read_val_score(stdout_path)
  File "./run_all.py", line 15, in read_val_score
    last_line = lines[-1]
IndexError: list index out of range
```

**Comment by iwiwi** [comment]
> RuntimeError: Found 0 files in subfolders of: /data/train

というエラーがでていますね。学習データが発見できていないようです。

書籍本文で説明しているようなディレクトリ構造にデータを配置できているか、指定しているパスは正しいか、などをご確認頂くと良いかと思います。

**Comment by tacsotai** [comment]
ありがとうございます。/data/trainにデータ自体は入れました。

```
 ls /data/train
cat.0.jpg      cat.1563.jpg  cat.4376.jpg  cat.7189.jpg  dog.0.jpg      dog.1563.jpg  dog.4376.jpg  dog.7189.jpg
cat.10000.jpg  cat.1564.jpg  cat.4377.jpg  cat.718.jpg   dog.10000.jpg  dog.1564.jpg  dog.4377.jpg  dog.718.jpg
```

**Comment by upura** [comment]
書籍 p.64 「3.4.1 データセットの準備」に示すディレクトリ構造になるようにデータセットを配置すると上手くいくかと存じます。

**Comment by upura** [comment]
ご参考までに、たとえば以下の Kaggle 上のサンプルコードのように実行すると、p.64 のようにデータを展開できます。
https://www.kaggle.com/code/takiba/kaggle-book-gokui-chapter3-dryrun
```bash
!unzip -q -n ../input/dogs-vs-cats-redux-kernels-edition/train.zip -d dogs_vs_cats
!unzip -q -n ../input/dogs-vs-cats-redux-kernels-edition/test.zip -d dogs_vs_cats
!mkdir -p dogs_vs_cats/train/cat
!mkdir -p dogs_vs_cats/train/dog
!mkdir -p dogs_vs_cats/test/unknown
!mv dogs_vs_cats/train/cat*.jpg dogs_vs_cats/train/cat
!mv dogs_vs_cats/train/dog*.jpg dogs_vs_cats/train/dog
!mv dogs_vs_cats/test/*.jpg dogs_vs_cats/test/unknown
```

**Comment by tacsotai** [comment]
ありがとうございます。
本自体は手元にあるのですが、3.4.1 見落としておりました。
本Issueはクローズします。
