### ISSUE TITLE
from delf import delf_config_pb2, extractor, utilsでエラー

### ISSUE THREAD

**Issue by idcnvrsn** [smly/kaggle-book-gokui#28]
手順通りにDockerイメージをbuild、runすると
08_extract_local_features.py
等の
from delf import delf_config_pb2, extractor, utils
の箇所で以下のようなエラーが出てしまいます。
同様の現象に遭遇して解決された方おられますでしょうか？

なお試しに、
RUN pip install protobuf==3.20.0
をDockerfileの末尾に追加して試すと
今度は
DNN library is not found.
が出てきます。

情報いただければ幸いです。

--------------------------------------ここからエラー発生時のメッセージ-------------------------------------------
root@03f636124b30:/workspace# python 08_extract_local_features.py
2023-07-02 03:37:36.041736: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-02 03:37:36.087231: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-02 03:37:36.829657: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/workspace/08_extract_local_features.py", line 10, in <module>
    from delf import delf_config_pb2, extractor, utils
  File "/opt/models/research/delf/delf/__init__.py", line 21, in <module>
    from delf.protos import aggregation_config_pb2
  File "/opt/models/research/delf/delf/protos/aggregation_config_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/opt/conda/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by idcnvrsn** [comment]
tensorflow ver2.11.1をインストールすることでとりあえず解決いたしました。

requirements.txtにtensorflowが記載されていますが今日現在ですとver2.12.0がインストールされ、これが相性が良くないようです(おそらくprotobufおよびcudnnに関して)。

Dockerfile末尾にRUN pip install tensorflow==2.11.1追加しダウングレードしたところ解消いたしました。
お騒がせしました。

**Comment by upura** [comment]
ご丁寧にありがとうございます。 @smly お手隙の際に確認をお願いします。

**Comment by smly** [comment]
ご報告ありがとうございます！大変助かります。
問題の再現を確認しました。https://github.com/smly/kaggle-book-gokui/pull/29 にて Tensorflow のバージョンを固定することで対応しました。
